export const products = [
  {
    id: 1,
    name: "Noir Exquis",
    brand: "L'ARTISAN PARFUMEUR",
    price: 210,
    image: "/images/optimized_perfume1.png",
    category: "MEN",
    scentType: "ORIENTAL",
    rating: 4,
    reviews: 6.8,
    description: "Notes of roasted coffee, orange blossom, and maple syrup.",
    isFavorite: false,
  },
  {
    id: 2,
    name: "Rozu Eau de Parfum",
    brand: "AESOP",
    price: 185,
    image: "/images/optimized_perfume2.png",
    category: "WOMEN",
    scentType: "FLORAL",
    rating: 5,
    reviews: 9.0,
    description: "Rose, Shiso, Galbacaceous Shifting and peach blossom accents",
    isFavorite: false,
  },
  {
    id: 3,
    name: "Gypsy Water",
    brand: "BYREDO",
    price: 270,
    image: "/images/optimized_perfume3.png",
    category: "UNISEX",
    scentType: "FRESH",
    rating: 4,
    reviews: 4.2,
    description: "Pine needles, sandalwood, and lemon",
    isFavorite: false,
  },
  {
    id: 4,
    name: "Ambre Sultan",
    brand: "SERGE LUTENS",
    price: 160,
    image: "/images/optimized_perfume4.png",
    category: "WOMEN",
    scentType: "ORIENTAL",
    rating: 5,
    reviews: 6.9,
    description: "Classic oriental amber with resin and oregano",
    isFavorite: false,
  },
  {
    id: 5,
    name: "Portrait of a Lady",
    brand: "FREDERIC MALLE",
    price: 390,
    image: "/images/optimized_perfume5.png",
    category: "WOMEN",
    scentType: "FLORAL",
    rating: 5,
    reviews: 4.7,
    description: "The unforgettable Turkish rose and patchouli blend",
    isFavorite: false,
  },
  {
    id: 6,
    name: "Philosykos",
    brand: "DIPTYQUE",
    price: 175,
    image: "/images/optimized_perfume6.png",
    category: "UNISEX",
    scentType: "FRESH",
    rating: 5,
    reviews: 5.0,
    description: "The memory of a Greek summer at Mount Pelion",
    isFavorite: false,
  },
];
